import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/style/globals.css';
import Header from '@/components/header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='min-h-screen flex flex-col items-center justify-between bg-background p-16 space-y-10'>
          <Header />
          <div className='grow w-5/6'>
            {children}
          </div>
          <div className='text-text'>Made by Thea Jenny Kolnes🦋</div>
        </main>
      </body>
    </html>
  );
}
